name: Publish Chrome Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

      # Zip up the extension
    - name: Zip extension folder
      run: |
        echo "Zipping extension folder..."
        ls -R dist   # List all files in dist for debugging
        zip -r extension.zip dist
        echo "Contents of extension.zip:"
        unzip -l extension.zip
        echo "File size details:"
        ls -lh extension.zip
    

      # Publish extension to Chrome Web Store
    - name: Upload to Chrome Web Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'upload'  # one of: upload, publish, testers
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        refresh_token: ${{ secrets.REFRESH_TOKEN }}
        extension_id: ${{ secrets.EXTENSION_ID }} 
        zip_file: 'extension.zip'          
    
    