name: Publish Chrome Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

      # Zip up the extension
    - name: Zip extension folder
      run: |
        echo "Zipping extension folder..."
        ls -R dist   # List all files in dist for debugging
        zip -r extension.zip dist
        echo "Contents of extension.zip:"
        unzip -l extension.zip
        echo "File size details:"
        ls -lh extension.zip
    

      # Publish extension to Chrome Web Store
    - name: Publish to Chrome Web Store
      uses: chromewebstore/chromewebstore-upload-cli@v1
      with:
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        source-file: "extension.zip"      # The file you zipped earlier
        auto-publish: true               # Automatically publish if upload succeeds
    
    